In [5]:
import pandas as pd

In [6]:
csv_file = "./Hard_labeled_Session20.csv"

In [7]:
csv = pd.read_csv(csv_file)
df = pd.DataFrame(csv)

In [8]:
df

,sensor_1,sensor_2,sensor_3,sensor_4,time_sec,Seconds,Fall_or_NotFall,Detailed_Label
0,1827,1930,1938,1837,0.000000,0.000000,NotFall,walking
1,1799,1973,1927,1815,0.000126,0.000126,NotFall,walking
2,1802,1989,1963,1812,0.000233,0.000233,NotFall,walking
3,1822,1978,1941,1759,0.000337,0.000337,NotFall,walking
4,1838,1947,1915,1775,0.000441,0.000441,NotFall,walking
...,...,...,...,...,...,...,...,...
11040,1986,1957,2000,2110,53.199469,53.199469,NotFall,post_activity
11041,1993,1968,1930,2096,53.204453,53.204453,NotFall,post_activity
11042,2018,1955,1952,2064,53.209162,53.209162,NotFall,post_activity
11043,1984,1972,1923,2086,53.214059,53.214059,NotFall,post_activity
11044,1994,1959,1859,2045,53.218956,53.218956,NotFall,post_activity

In [9]:
df[["sensor_1", "time_sec", "Fall_or_NotFall"]]

       sensor_1   time_sec Fall_or_NotFall
0          1827   0.000000         NotFall
1          1799   0.000126         NotFall
2          1802   0.000233         NotFall
3          1822   0.000337         NotFall
4          1838   0.000441         NotFall
...         ...        ...             ...
11040      1986  53.199469         NotFall
11041      1993  53.204453         NotFall
11042      2018  53.209162         NotFall
11043      1984  53.214059         NotFall
11044      1994  53.218956         NotFall

[11045 rows x 3 columns]

In [10]:
sensor_1 = df[["sensor_1", "time_sec", "Fall_or_NotFall"]]

In [11]:
sensor_1.head()

   sensor_1  time_sec Fall_or_NotFall
0      1827  0.000000         NotFall
1      1799  0.000126         NotFall
2      1802  0.000233         NotFall
3      1822  0.000337         NotFall
4      1838  0.000441         NotFall

In [12]:
sensor_1[sensor_1["Fall_or_NotFall"] == "Fall"]

      sensor_1   time_sec Fall_or_NotFall
6175      1798  28.874548            Fall
6176      2173  28.879524            Fall
6177      2483  28.884483            Fall
6178      4095  28.889350            Fall
6179      4015  28.894408            Fall
...        ...        ...             ...
6556      1774  30.779362            Fall
6557      1786  30.784478            Fall
6558      1823  30.789422            Fall
6559      1910  30.794414            Fall
6560      2005  30.799378            Fall

[386 rows x 3 columns]

In [13]:
sensor_1.tail()

       sensor_1   time_sec Fall_or_NotFall
11040      1986  53.199469         NotFall
11041      1993  53.204453         NotFall
11042      2018  53.209162         NotFall
11043      1984  53.214059         NotFall
11044      1994  53.218956         NotFall

In [14]:
sensor_1 = sensor_1.rename(columns={"sensor_1" : "value"})

In [15]:
sensor_1

       value   time_sec Fall_or_NotFall
0       1827   0.000000         NotFall
1       1799   0.000126         NotFall
2       1802   0.000233         NotFall
3       1822   0.000337         NotFall
4       1838   0.000441         NotFall
...      ...        ...             ...
11040   1986  53.199469         NotFall
11041   1993  53.204453         NotFall
11042   2018  53.209162         NotFall
11043   1984  53.214059         NotFall
11044   1994  53.218956         NotFall

[11045 rows x 3 columns]

In [23]:
fall = sensor_1[["value", "time_sec", "Fall_or_NotFall"]][(sensor_1["value"] == sensor_1["value"].max()) & (sensor_1["Fall_or_NotFall"] == "Fall")]

In [24]:
fall

      value   time_sec Fall_or_NotFall
6178   4095  28.889350            Fall
6184   4095  28.919399            Fall
6232   4095  29.159399            Fall
6233   4095  29.164329            Fall
6234   4095  29.169532            Fall
6245   4095  29.224381            Fall
6255   4095  29.274346            Fall
6256   4095  29.279719            Fall
6257   4095  29.284381            Fall
6258   4095  29.289304            Fall
6259   4095  29.294761            Fall

In [25]:
fall = sensor_1[["value", "time_sec"]][(sensor_1["time_sec"] >= fall["time_sec"].min() - 5) & (sensor_1["time_sec"] <= fall["time_sec"].max() + 5)]

In [26]:
fall

      value   time_sec
5178   1901  23.889463
5179   1841  23.894286
5180   1862  23.899329
5181   1920  23.904550
5182   1953  23.909501
...     ...        ...
7255   1830  34.274403
7256   1824  34.279342
7257   1855  34.284433
7258   1825  34.289364
7259   1830  34.294306

[2082 rows x 2 columns]

In [27]:
fall = fall["value"]

In [28]:
fall

5178    1901
5179    1841
5180    1862
5181    1920
5182    1953
        ...
7255    1830
7256    1824
7257    1855
7258    1825
7259    1830
Name: value, Length: 2082, dtype: int64

In [29]:
fall.to_csv("mock.csv", index=False)

In [30]:
fall = pd.DataFrame(pd.read_csv("mock.csv"))

In [31]:
len(fall)

2082